# Travis CI script

language: c

#   Build-check-install all subprojects
before_script:

#   GSL
- git clone git://github.com/imatix/gsl.git
- ( cd gsl/src; make; sudo make install )

#   libsodium
- git clone git://github.com/jedisct1/libsodium.git
- ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

#   libzmq
- git clone git://github.com/zeromq/libzmq.git
- ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

#   CZMQ
- git clone git://github.com/zeromq/czmq.git
- ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

#   Build and check this project
script:
- ./autogen.sh
- ./configure && make check
- sudo make install
