language: c

#   Install dependencies first
before_script:
- git clone git://github.com/imatix/gsl.git
- cd gsl/src
- make
- sudo make install
- cd ../..
- git clone git://github.com/jedisct1/libsodium.git
- git clone git://github.com/zeromq/libzmq.git
- git clone git://github.com/zeromq/czmq.git
- for project in libsodium libzmq czmq; do
-     cd $project
-     ./autogen.sh
-     ./configure && make check
-     sudo make install
-     sudo ldconfig
-     cd ..
- done

#   Build and check this project
script:
- ./autogen.sh
- ./configure && make check
- sudo make install

- cd skeleton
- ./autogen.sh
- ./configure && make check

